# Generated by Django 5.0.6 on 2025-08-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_applications_count_jobpost_job_type_and_more'),
        ('jobs', '0002_skill_jobpost_skills'),
    ]

    operations = [
    ]
